# Generated by Django 3.2 on 2023-05-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
