# Generated by Django 3.2 on 2023-05-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='estimated_dispatch',
        ),
        migrations.RemoveField(
            model_name='item',
            name='how_many_in_stock',
        ),
    ]
