# Generated by Django 3.2 on 2023-05-08 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField(max_length=500)),
                ('image', models.ImageField(
                    blank=True, null=True, upload_to='')),
                ('featured', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('commission', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commissions.commissions')),  # noqa
                ('item', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item')),  # noqa
                ('user', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),  # noqa
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
